on:
  release:
    types: [published]

env:
  NODE_VERSION: '10.x'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: npm package
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        registry-url: https://registry.npmjs.org/
    - name: npm install, build, and test
      run: |
        npm install
        npm run build:component
        npm run build:less
        npm publish
      env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}